## CONTROL
AFK_TIMEOUT = 300 # 5 minutes (set to zero to diable)
HOLD_TO_QUIT_SECONDS = 1.5
# COOLDOWN_DIRECTIONAL_SECONDS = 0.05
COOLDOWN_DIRECTIONAL_SECONDS = 0.1

## DISPLAY / UI
FPS = 80
BORDER_WIDTH = 6
PLAYFIELD_WIDTH = 4000
PLAYFIELD_HEIGHT = 4000

## GAMEPLAY
LIFE_SUCK_RATE = 1
AGENT_SPAWN_INTERVAL_SECONDS = 0.05
MAX_AGENTS = 900


## PLAYER
PLAYER_STARTING_POS = (20, 20)
WALL_BOUNCE_ATTENUATION = 0.80
TOP_SPEED = 100

#NOTE: This would create a circular import
# from grub.view.camera import Camera
# CAMERA: Camera = None

# from grub.actor.player import Player
# PLAYER: Player = None
